AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens carousel static website deploy on s3 through cloudfront and route 53
Parameters:
  MYDomainName:
    Description: DNS Name of existing Amazon Route 53 hosted zone like asim-is-awesome.com
    Type: AWS::Route53::HostedZone::Id
  MYSUBDomainName:
    Description: Full domain name for the App. like AWS.asim-is-awesome.com
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
Resources:
  KittensBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: !Ref MYDomainName
      WebsiteConfiguration: 
        IndexDocument: index.html

  MYBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KittensBucket
      PolicyDocument:     
        Statement:
          - Sid: PublicReadforStaticWebsite
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref 'KittensBucket', /*]]

  MYCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Ref MYSUBDomainName
      DomainValidationOptions:
        - DomainName: !Ref MYSUBDomainName
          HostedZoneId: !Ref MYDomainName
      ValidationMethod: DNS

  MYCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref MYSUBDomainName
        Comment: Cloudfront Distribution pointing to Kittens S3 bucket
        DefaultCacheBehavior: 
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          TargetOriginId: KittensOrigin
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: 'http2'
        Origins:
        - DomainName: !Select [2, !Split ["/", !GetAtt KittensBucket.WebsiteURL]]
          Id: KittensOrigin
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref MYCertificate
          SslSupportMethod: sni-only

  KittensRecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref MYDomainName
      RecordSets: 
        - Name: !Ref MYSUBDomainName
          Type: A
          AliasTarget:
            DNSName: !GetAtt MYCloudfront.MYDomainName
            HostedZoneId: Z2FDTNDATAQYW2


Outputs:
  BucketName: 
    Description: S3 Bucket URL for Kittens Website
    Value: !GetAtt KittensBucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront
    Value: !GetAtt MYCloudfront.MYDomainName
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref MYSUBDomainName